- Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/ElasticSearchQueryBuilder.php
Avoid errors for count requests when certain unsupported
fields are present in the request.
> [BUGFIX] Prevent error when counting using existing query

- README.md
Related: Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#70, Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#71, Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#72, f8999fc42, e54aaf50f, 2c57065
> [TASK] updated documentation for working with dates

- README.md
> [BUGFIX] correct filename elasticsearch.yml in documentation

- Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Indexer/NodeIndexer.php
In ES the ID property is unique inside a single document type. With the
current implementation, after a NodeType change, we create a new document
with the new NodeType, but the old one stay in the index.
This change solve the issue with a DELETE query to check is an other
document share the same _id before indexing new values.
> [BUGFIX] After changing NodeType indexes contains two documents

- Configuration/NodeTypes.yaml
- Configuration/Settings.yaml
- README.md
This change add default mapping for Asset, and update ImageInterface and
date type name based on change in Neos 2.0.
> [TASK] Update default configuration per type

- README.md
- fix build icon
- remove TYPO3 references
> [TASK] update README a little

- .travis.yml
- Configuration/Testing/WithoutLanguageFallback/Settings.yaml
- Tests/Functional/Eel/ElasticSearchQueryTest.php
> [TASK] Enable elasticsearch for functional tests in travis

- README.md
The documentation contains configuration hints/examples for Elasticsearch up to 1.4.
This changes the documentation to state that versions up to 1.7 are actually working and
provides configuration examples for later versions as well.
> [TASK] Adjust configuration docs for Elasticsearch versions

- Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/ElasticSearchQueryBuilder.php
- Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/ElasticSearchQueryResult.php
- README.md
- Tests/Functional/Eel/ElasticSearchQueryTest.php
It offers a simple term suggestion on all fields (termSuggestions(aTerm)) or the possibility to
use your own suggestion query (suggestion("my-suggestions", suggestionDefinition))
> [FEATURE] implements the suggest feature of elasticsearch

- Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Indexer/NodeIndexer.php
This change fix a regressing who break indexing for site without
dimensions configuration or without the languages dimension.
Fix #112
> [BUGFIX] Fix indexing without dimension or with custom dimensions

- Configuration/NodeTypes.yaml
Taking over #124 as there's no feedback from @jrenggli
> BUGFIX: Index Document titles by default

- Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Indexer/NodeIndexer.php
These changes make sure the fulltext index is correctly updated when nodes are hidden or removed.
> BUGFIX: Correctly handle removed/hidden nodes in fulltext index

- README.md
Change all occurrences of TYPO3 package names
Fix Repository URLs
> TASK: Update Readme

- Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Command/NodeIndexCommandController.php
- Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Indexer/NodeIndexer.php
This basically fixes an undefined variable usage.
> BUGFIX: Set workspace if specified for nodeindex:indexnode command

- README.md
Added documentation about multi site configuration for a single elasticsearch server
> TASK: Update documentation about custom index name

- Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Factory/AbstractDriverSpecificObjectFactory.php
- Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Factory/QueryFactory.php
- Configuration/Objects.yaml
Separate driver and query factory
> TASK: Refactor the object factory

- README.md
ElasticSearchContentRepositoryAdaptor != ElasticSearch.ContentRepositoryAdaptor
> BUGFIX: Change path for ES version setting

- Configuration/Settings.yaml
> BUGFIX: Exclude suggest from count query

- Classes/Driver/Version1/Query/FilteredQuery.php
- Classes/Eel/ElasticSearchQueryBuilder.php
> BUGFIX: Escape fulltext searchQuery

- Classes/Command/NodeIndexCommandController.php
Fixes Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#208
> BUGFIX: Use correct NodeIndexerInterface in command controller

- Classes/Indexer/NodeIndexer.php
- adjusts a parameter comment to be more clear
- removes the use of two extraneous method parameters
> TASK: Two small tweaks to the `NodeIndexer`

- .travis.yml
- Classes/Command/NodeIndexCommandController.php
- Classes/Driver/Version1/DocumentDriver.php
- Classes/Driver/Version1/IndexDriver.php
- Classes/Driver/Version1/IndexerDriver.php
- Classes/Factory/AbstractDriverSpecificObjectFactory.php
- Classes/Factory/DriverFactory.php
This change
- removes imports of non-existing DriverInterface
- updates Elasticsearch used in Travis to latest versions
- does some refactoring in NodeIndexCommandController
- adds use statements  in NodeIndexCommandController
> TASK: Some general (style) tweaks to code

- Classes/ElasticSearchClient.php
- Classes/Service/IndexNameStrategy.php
- Classes/Service/IndexNameStrategyInterface.php
Currently the only way to define the Index name, is by Settings. With
this new Interface, it's now possible to implement other Strategies.
> FEATURE: IndexName Strategy

- .travis.yml
- Classes/Command/NodeIndexCommandController.php
- Classes/Driver/AbstractNodeTypeMappingBuilder.php
- Classes/Driver/NodeTypeMappingBuilderInterface.php
- Classes/Driver/Version1/DocumentDriver.php
- Classes/Driver/Version1/IndexerDriver.php
- Classes/Driver/Version1/Mapping/NodeTypeMappingBuilder.php
- Classes/Driver/Version2/DocumentDriver.php
- Classes/Driver/Version2/IndexerDriver.php
- Classes/Driver/Version2/Mapping/NodeTypeMappingBuilder.php
- Classes/Driver/Version5/DocumentDriver.php
- Classes/Driver/Version5/IndexDriver.php
- Classes/Driver/Version5/IndexerDriver.php
- Classes/Driver/Version5/Mapping/NodeTypeMappingBuilder.php
- Classes/Driver/Version5/Query/FilteredQuery.php
- Classes/Driver/Version5/Query/FunctionScoreQuery.php
- Classes/Driver/Version5/RequestDriver.php
- Classes/Driver/Version5/SystemDriver.php
- Classes/Factory/NodeTypeMappingBuilderFactory.php
- Classes/Indexer/NodeIndexer.php
- Configuration/Objects.yaml
- Configuration/Settings.yaml
- Configuration/Testing/ElasticVersion5/Settings.yaml
- Configuration/Testing/NodeTypes.yaml
- Documentation/ElasticConfiguration-2.x.md
- Documentation/ElasticConfiguration-5.x.md
- Documentation/ElasticMapping-5.x.md
- README.md
- Tests/Functional/Eel/ElasticSearchQueryTest.php
These changes enable support for Elasticsearch v5 via a new driver and changes
in the internal handling of building type mappings.
> FEATURE: Support for Elasticsearch v5

- Classes/Driver/Version5/SystemDriver.php
Using _stats instead of _status endpoint
fixes: #257
> BUGFIX: Fix cleanup command

- Classes/Driver/Version5/Mapping/NodeTypeMappingBuilder.php
- Classes/Driver/Version5/Query/FilteredQuery.php
- Configuration/NodeTypes.yaml
- Configuration/Settings.yaml
- README.md
- Tests/Functional/Eel/ElasticSearchQueryTest.php
This is a breaking change and leads to a new major release. 
- Adds new tests for fulltext and hghlighting
- Fixes highlighting
> !!! TASK: Remove usage of the _all field

- Classes/Driver/AbstractQuery.php
- Classes/Driver/QueryInterface.php
- Classes/Eel/ElasticSearchQueryBuilder.php
- README.md
This implements an convinent API to build more like this queries.
For details see the [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/query-dsl-mlt-query.html)
> FEATURE: More like this

- Classes/Eel/ElasticSearchQueryBuilder.php
Reverts Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#278
> Revert "TASK: Expose cache flag on es query"

- Classes/Eel/ElasticSearchQueryBuilder.php
- README.md
Works basically as a negation of the exactMatch method
> FEATURE: Add an exclude method to the ES query builder

- Classes/Eel/ElasticSearchQueryBuilder.php
In case only the live workspace is indexed to elastic and a new document
is only available in a personal workspace, an exceptoion was
thrown. Now the error is logged and ignored
> BUGFIX: No exception when document not found in MLT

- .travis.yml
> TASK: Exchange java package in travis configuration

- Classes/Command/NodeTypeCommandController.php
- Classes/Service/NodeTypeIndexingConfiguration.php
- Configuration/Testing/Settings.yaml
- README.md
- Tests/Functional/Service/NodeTypeIndexingConfigurationTest.php
- also adds a method to get a list of nodeTypes and if they are indexed
> FEATURE: Add show indexable command

- Classes/Command/NodeIndexCommandController.php
- Classes/Eel/ElasticSearchQueryBuilder.php
- Classes/Indexer/NodeIndexer.php
- Configuration/Settings.Neos.ContentRepository.Search.yaml
- README.md
- Tests/Functional/Eel/ElasticSearchQueryTest.php
This ads a prefix() filter operator to the QueryBuilder
> FEATURE: Prefix query operation

- Classes/Eel/ElasticSearchQueryBuilder.php
- README.md
Filters documents that include only hits that exists within a specific distance from a geo point.
> FEATURE: Add geoDistance operation

- README.md
> TASK: Add the status of the package version

- Classes/Driver/Version5/DocumentDriver.php
As we have _delete_by_query in ES 5, this is a way simpler solution
#closes #333
> TASK: Exchange scrolling and deleting by simple _delete_by_query

- Classes/AssetExtraction/IngestAttachmentAssetExtractor.php
Check for successful extraction. Return an error if extraction failed.
> BUGFIX: Do not blindly use array keys

- .travis.yml
- Classes/Command/NodeIndexCommandController.php
Previously, the `nodeindex:indexnode` command exited as soon as a node was not present in one of the configured dimensions.
Now it returns a table that shows which variants where indexed: 
```
+-----------+--------------------------------+----------------------------------------+-----------+
| Workspace | NodeType                       | Dimensions                             | State     |
+-----------+--------------------------------+----------------------------------------+-----------+
| live      | -                              | {"country":["corp"],"language":["de"]} | not found |
| live      | -                              | {"country":["aut"],"language":["de"]}  | not found |
| live      | -                              | {"country":["che"],"language":["de"]}  | not found |
| live …
```
> BUGFIX: nodeindex:indexnode handles multiple dimensions

- Classes/Eel/ElasticSearchQueryBuilder.php
- Tests/Functional/Eel/ElasticSearchQueryTest.php
- Tests/Unit/Eel/ElasticSearchQueryBuilderTest.php
> TASK: Only apply the size parameter if set

- Classes/Indexer/NodeIndexer.php
-> to calculateDocumentIdentifier
> TASK: Remove context path calculation which is moved 

- Classes/Indexer/NodeIndexer.php
> TASK: Remove contentDimensionCombination loop in nodeIndexer

- Configuration/Settings.yaml
> TASK: Add mapping for Elasticsearch 7.x to settings

- Classes/Driver/Version6/Mapping/NodeTypeMappingBuilder.php
Replicates 97aa56fe2b1f30e16b53c766c2ecda954a5cae08 for the v7 branch.
> TASK: Allow to unset elasticSearchMapping parameters

- README.md
... live from NeosCon Online 2021 :)
> BUGFIX: fix typo in README.md

- Classes/AssetExtraction/IngestAttachmentAssetExtractor.php
- Configuration/Settings.yaml
Huge files may exceed the avalaible memory and should thus
not be ingested.
> FEATURE: Define max file size for ingesting attachments

- Classes/Eel/ElasticSearchQueryBuilder.php
> BUGFIX: Include all base workspaces in neos_workspace

- Classes/Driver/Version6/Mapping/NodeTypeMappingBuilder.php
- Configuration/NodeTypes.Override.Document.yaml
- Configuration/NodeTypes.Override.Hidable.yaml
> BUGFIX: Fix node reference mapping
