Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Command/NodeTypeCommandController.php

The method getFullConfguration() on the NodeTypeManager does not exist
(anymore), so collect configuration in a different way.

[BUGFIX] nodetype:show uses undefined method getFullConfiguration()

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Indexer/NodeIndexer.php

Incorrect escaping of the newline character used in the flush method
in the NodeIndexing, resulting in incorrect log data if multiple
response lines were returned.

[BUGFIX] Handle response in NodeIndexing flushing correctly

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/ElasticSearchQueryBuilder.php

Usage::
searchFilter = TYPO3.TypoScript:RawArray {
constraint1 = 'a'
constraint2 = TYPO3.TypoScript:RawArray {
0 = 'b'
1 = 'c'
}
}
searchQuery = ${Search.queryFilterMultiple(this.searchFilter)}

[FEATURE] ``queryFilterMultiple`` operation for QueryBuilder

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/ElasticSearchQuery.php
Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/ElasticSearchQueryBuilder.php
Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/ElasticSearchQueryResult.php

This change is based upon #66, makes #62 obsolete and re-implements #63.
To be used in conjunction with https://github.com/skurfuerst/Flowpack.SearchPlugin/tree/dev-query-result

Highlighting Support in ElasticSearch

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Indexer/NodeIndexer.php
composer.json

Removes the user land definition of json_last_error_msg()

[TASK] Use PHP 5.5 as minimum requirement

---

Configuration/NodeTypes.yaml

Changed the "_hiddenBeforeDateTime" and "_hiddenAfterDateTime" Search Index Configuration to give over
the PHP's currently configured Timezone. That way, considering everything is configured correctly in the server
(same locale as PHP), "now" and all other queries should work as expected.
Related: Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#70

[BUGFIX] Hide Before/After Dates indexed with PHP timezone

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/ElasticSearchQueryBuilder.php

This change adds a terms filter to the query method that includes the
context dimension values to fetch only matching documents. This works
for most dimension usages except complex use-cases with overlapping
fallback chains.
The result count should now be correct when querying nodes with multiple
variants, so it solves at least one problem of #44.

[BUGFIX] Correctly filter for dimension combinations in query

---

Tests/Unit/Eel/ElasticSearchQueryBuilderTest.php

Extend the $mockContext with an method getDimensions that returns an empty array to fix the current tests

[TASK] Fix Unittests

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/ElasticSearchQueryBuilder.php
Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/ElasticSearchQueryResult.php
README.md
Tests/Unit/Eel/ElasticSearchQueryBuilderTest.php

This change implements a new function addSimpleAggregation() and a new low-level function addSubAggregation to add (sub-) aggregatons to a elasticsearch request.
Usage to get aggregation for property "color" in a node Vendor.Name:NodeType:
`nodes = $Search.query(site).nodeType("Vendor.Name:NodeType").addSimpleAggregation("color", "color").execute() `
To get your aggregationResults access {nodes.aggregations} in your fluid template.
This change also allows you to add sub-aggregations:
`nodes = $Search.query(site).nodeType("Vendor.Name:NodeType").addSimpleAggregation("color", "color").addSimpleAggregation("type", "type", "terms", "color" ).execute() `

[TASK] Add aggregation functionality

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/ElasticSearchQueryBuilder.php
Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/ElasticSearchQueryResult.php
Configuration/Testing/Settings.yaml
Tests/Functional/Eel/ElasticSearchQueryTest.php

Refactor the queryBuilder and the result object as a basis for further extensions and improvements.
ElasticSearchQueryBuilder::fetch() now returns an array including the nodes and the other meta data results. The ElasticSearchQueryResult still provides the nodes through its ArrayAccess implementation but also returns additional data like aggregations and suggestions through specific getters.
Also added a first functional test. All tests are failing right now due to existing bugs.
Jira: IN-4

[TASK] Querybuilder refactoring

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/ElasticSearchQueryResult.php
Tests/Unit/Eel/ElasticSearchQueryBuilderResultTest.php

If you don't request aggregations in your Query but you do access the aggregations in Fluid it results in an Exception. This change will return an empty array if there are no aggregations.
Fixes: IN-7

[BUGFIX] If no aggregations are set getAggregations will brake

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/ElasticSearchQueryBuilder.php
Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/ElasticSearchQueryResult.php
Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/ViewHelpers/GetHitArrayForNodeViewHelper.php
README.md
Tests/Functional/Eel/ElasticSearchQueryTest.php
Tests/Unit/ViewHelpers/GetHitArrayForNodeViewHelperTest.php

This changes adds a generic sort operation that can be used to create any kind of sorting that ElasticSearch supports.

[TASK] Add generic sort operation

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/ElasticSearchQuery.php
Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/ElasticSearchQueryBuilder.php

A query with the same payload will return the same content from ES, this change adds a runtime cache and implement the support of the ```$cacheResult``` in ```QueryInterface::execute```.
This change also enable the runtime cache by default in the ```ElasticSearchQueryBuilder```

[TASK] Add a runtime QueryResult Cache

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Indexer/NodeIndexer.php

The NodeIndexer tries to retrieve the list of index aliases with a
GET request like `http://localhost:9200/*/_alias/typo3cr´. However,
newer API versions don't seem to support this URL format and fail with
a PatternSyntaxException (Dangling meta character '*').
This fix changes the pattern to `http://localhost:9200/_alias/typo3cr`
which seems to work with both, newer and older API versions.
Tested with Elasticsearch 1.5.2 and 1.7.2.

BUGFIX: Retrieval of aliases fails with newer API versions

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Indexer/NodeIndexer.php

Use proper way of mapping node type name to `_type` in index.
Closes #115

BUGFIX: Fulltext parts are lost on document update

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/ElasticSearchQueryBuilder.php

This change replace $this->request by $this->getRequest() call during
request execution. This is useful when creating custom query builder
integration that can modifiy the request before execution.

TASK: Call method getRequest to make it more easy to extend

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Command/NodeIndexCommandController.php
Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Service/IndexWorkspaceTrait.php

This change extract the logic used to index a workspace with all dimensions from the controller to a trait to make this logic reusable. The logic is also refactored to remove some object property (to avoid collision when a class use this trait). A new callback is introduced to execute code after the workspace indexing (used in the command controller for shell output).

TASK: Extract logic to index workspace from the controller to a trait

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Service/IndexWorkspaceTrait.php

This prevents memory being flooded with all node / dimension combinations data during indexing by clearing caches when a dimension combination was completely indexed

TASK: Free memory during indexing after each dimension combination

---

.travis.yml
Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Indexer/NodeIndexer.php

This change implements the newly introduced `BulkNodeIndexerInterface` for
the TYPO3.TYPO3CR.Search package. When enabled this skips the check for
duplicate nodes with a different node type. This check is only useful when
changing the node type (live indexing). During the initial indexing this can
speed up the process quite a lot for big indexes.

TASK: Implement BulkNodeIndexerInterface in NodeIndexer

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/ElasticSearchQueryBuilder.php
Tests/Unit/Eel/ElasticSearchQueryBuilderTest.php

This fixes ElasticSearchQueryBuilder::getTotalItems() that was checking
a non-existing result index total to retrieve the number of search results.
Fixes: #139

BUGFIX: Correctly determine number of total search results

---

README.md

The current link to the Flowpack.Elasticsearch package links to the 'contentrepositoryadaptor'-package in the readme file.

BUGFIX: Correct link to Flowpack.Elasticsearch

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Command/NodeIndexCommandController.php

The contentDimensionPresetSource was typehinted to the Neos
ContentDimensionPresetSourceInterface from the TYPO3.Neos
package. This interface is based on the corresponding
ContentDimensionPresetSourceInterface interface in the TYPO3.TYPO3CR
package.
As the command controller does not make use of the additional
method on the interface in the Neos package the use of it is
useless.
This change changes the type hint to the TYPO3.TYPO3CR package
so the Elastic content repository adaptor can be installed without
the TYPO3.Neos package.

BUGFIX: Unneeded dependency on TYPO3.Neos package

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/ElasticSearchQueryBuilder.php
Tests/Functional/Eel/ElasticSearchQueryTest.php
Tests/Unit/Eel/ElasticSearchQueryBuilderTest.php

The ElasticSearchQueryBuilder::query searches only below the given context
document.
One example when this is wrong is when you search from the site node, which
you use as the homepage - in this case the actual "homepage" would not be
searched.

BUGFIX: Include the context document in the query result

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Command/NodeIndexCommandController.php

This change introduce a new CLI command to index a single node in the current index:
flow nodeindex:indexnode --identifier c480b96f-ee9c-b304-3feb-570182a08236

TASK: Add a CLI command to index a node by identifier and workspace name

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Service/IndexWorkspaceTrait.php

This change solve issue with PHP 7.1 that don't allow it.

BUGIFX: Remove useless variable in traverseNodes callback

---

Configuration/NodeTypes.yaml

This will correctly index the status of the “Hide in menus” checkbox
on documents.

FEATURE: Index the node property `_hiddenInIndex`

---

Classes/Indexer/NodeIndexer.php

`$mapHitToDeleteRequest` was always returning `null` (i.e. it was `void`).
fixes #159.

BUGFIX: Bulk request needs to end with \n

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Driver/AbstractQuery.php
Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Driver/QueryInterface.php
Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/ElasticSearchQueryBuilder.php
README.md
Tests/Unit/Eel/ElasticSearchQueryBuilderTest.php

By default, elasticsearch returns 10 buckets for a term aggregation.
This change makes the size value configurable via fusion.
Also improves some header comments.
This is a rebuild-PR against new 3.0.

FEATURE: Make amount of buckets configurable via fusion

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/ElasticSearchQueryBuilder.php
Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/ElasticSearchQueryResult.php
Tests/Functional/Eel/ElasticSearchQueryTest.php

Before the result of ``getSuggestions`` returned the suggestion of a search term if the term only consisted of one word. When the search term consisted of two words it returned the complete array. This is an absolutely unexpected behavior. It was also only possible to access the first defined suggest term.
This change now returns the complete suggestion array, so it behaves like the comparable aggregation getter.

!!! TASK: Adjust the result of getSuggestions

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Eel/SearchResultHelper.php
Configuration/Settings.yaml

The change in https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/pull/184 gives you the complete and consistent access to the suggestion array. But this now also means, that you have to do the calculations to build a "didYouMean" feature completely on your own in Fusion.
This helper makes that task a lot more convenient.
Example Usage:
```
query = ${Search.query(site).fulltext(this.searchTerm).termSuggestions(this.searchTerm)}
didYouMean = ${SearchResult.didYouMean(this.searchQuery.execute(), 0.5)}
```

FEATURE: Add SearchResult Eel Helper

---

Classes/Command/NodeIndexCommandController.php
Classes/Driver/Version2/SystemDriver.php

In the cleanup command there was a regression introduced with 314ecac2cb88055b724943e9ad96bb6fb10f1cac where it tried to log an object.
In ESv2 /_status was removed in favor of /_stats (see https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking_20_stats_info_and_literal_cat_literal_changes.html#_index_status_api and https://www.elastic.co/guide/en/elasticsearch/reference/2.0/indices-status.html).

BUGFIX: fix nodeindex:cleanup command in Elasticsearch >= 2.x

---

Classes/Driver/Version1/IndexerDriver.php
Classes/Driver/Version2/IndexerDriver.php

For some reason `__fulltextParts` is sometimes an empty array which prevents the groovy script from "putting" into it. In this case, this pull requests reinitializes the `_fulltextParts`as a new hashmap.

TASK: Check type of __fulltextParts to ensure it is always a hash map

---

Classes/Command/NodeIndexCommandController.php
Classes/Driver/Version2/SystemDriver.php

- In the cleanup command there was a regression introduced with 314ecac2cb88055b724943e9ad96bb6fb10f1cac where it tried to log an object.
- In ESv2 /_status [was removed](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking_20_stats_info_and_literal_cat_literal_changes.html#_index_status_api) in [favor of /_stats](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/indices-status.html).
This replaces PR #200 and targets branch 3.0.

BUGFIX: Fix nodeindex:cleanup command for ES >= 2.0

---

Classes/Flowpack/ElasticSearch/ContentRepositoryAdaptor/Command/NodeIndexCommandController.php

When the name of a non-existing workspace was given to `nodeindex:build`,
that work was implicitly created (due to some legacy default behaviour of the
content repository).
This change adds a check and stops when the workspace does not exist.
The `nodeindex:indexnode` command did not cause workspace creation,
but now shows an error message, instead of an exception. Covfefe!
Fixes issue #213

BUGFIX: Avoid creating workspaces in nodeindex:build

---

Classes/Command/NodeIndexCommandController.php

The NodeIndexCommandController used a trait from Neos
which adds just little value while adding a strong dependency
to Neos which conflicts with the content repository requirement
to run 'standalone'.
Resolves #209

BUGFIX: Remove unneeded depency on Neos

---

Classes/Driver/Version1/IndexDriver.php

If you search for index that not exists, it triggers error (and should not as the code handle the creation after that).
And sometimes (perhaps due to utilisation of Elastic Cloud), treated response is null/not array so an error is triggered. Simply ensure here a empty array is returned if treated content is not an array.

BUGFIX: Index by alias, treated content

---

Classes/Eel/ElasticSearchQueryBuilder.php

The fix introduced to escape the query (see #198) also adds quotes around, so it's not
a full text query anymore.
This change trims the output of `json_encode()` to remove the quotes again.
Fixes #197

BUGFIX: Fulltext query is broken

---

README.md

Corrects the `Neos.ContentRepository.Search` ViewHelper namespace.

BUGFIX: Adjust `Neos.ContentRepository.Search` ViewHelper namespace

---

Classes/Eel/ElasticSearchQueryBuilder.php

Instead of simply ignoring an exception during query execution the
`ElasticSearchQueryBuilder` will now log an exception during `fetch()`
and return an empty result.

TASK: Catch query errors and return empty result

---

Classes/Driver/AbstractNodeTypeMappingBuilder.php
Classes/Driver/NodeTypeMappingBuilderInterface.php
Classes/Driver/Version1/DocumentDriver.php
Classes/Driver/Version1/IndexerDriver.php
Classes/Driver/Version1/Mapping/NodeTypeMappingBuilder.php
Classes/Driver/Version2/DocumentDriver.php
Classes/Driver/Version2/IndexerDriver.php
Classes/Driver/Version5/IndexerDriver.php
Classes/Driver/Version5/Mapping/NodeTypeMappingBuilder.php
Classes/Indexer/NodeIndexer.php

Refactor the static method nodeTypeMappingBuilder::convertNodeTypeNameToMappingName 
to non-static.
This is needed as the nodeTypeMappingBuilder is now a configurable and injected object
which can be driver specific

TASK: Refactor nodeTypeMappingBuilder::convertNodeTypeNameToMappingName

---

Classes/Driver/QueryInterface.php
Classes/Driver/Version1/Query/FilteredQuery.php
Classes/Driver/Version5/Query/FilteredQuery.php
Classes/Eel/ElasticSearchQueryBuilder.php
README.md

In order to configure the `query_string` query, for example, to set the `default_operator` to `AND`
you can now pass additional options to the fulltext Eel operation

FEATURE: Make fulltext options configurable

---

Classes/Driver/Version5/Mapping/NodeTypeMappingBuilder.php

Include_in_all is deprecated with elasticsearch 5.x and raises warnings on index creation

TASK: Migrate include_in_all to copy_to for ES 5.x

---

Classes/Driver/Version5/IndexerDriver.php

For yet unknown reasons, __fulltextParts and __fulltext are initialized
as type ArrayList instead of HashMap and operations like containsKey()
fail. The painless script now checks the type and re-initializes it
if it is not a HashMap

BUGFIX: Make sure __fulltextParts and __fulltext are of type map

---

Classes/Eel/ElasticSearchQueryBuilder.php
README.md
Tests/Functional/Eel/ElasticSearchQueryTest.php

In order to calculate the maximum cache time of a rendered collection of fetched nodes, we need a method similar to the `.cacheLifetime()` flowQuery method.

FEATURE: Add a method to calculate the cache lifetime of all nodes

---

Configuration/Objects.yaml

When you try to extend the ElasticSearchQueryBuilder and with this adding a second class implementing
the QueryBuilderInterface, the ObjectManager is not able to automatically select the implementing class
any more. This adds this missing configuration

TASK: Configure ESQueryBuilder as implementation of the QueryBuilderInterface

---

Classes/Dto/SearchResult.php
Classes/Eel/ElasticSearchQueryBuilder.php

Result handling in the ES adapter is a bit messy. 
In order to adjust the result evaluation (where the actual hits are coming from), this code is extracted into a separate method which returns a result dto.

TASK: Extract result evaluation

---

Classes/Eel/ElasticSearchQueryBuilder.php

This change introduces a new method `executeUncahced` to the ElasticSerachQueryBuilder. This method will actually execute the ElasticSearchQuery but the result will be uncached.

TASK: Add a new `executeUncached()` method to ElasticSearchQueryBuilder

---

README.md

Docs: Fix typo in suggestion query

---

Classes/Eel/ElasticSearchQueryBuilder.php

Sometimes certain requests return some fields under `fields` path. In that case the current logic tries to search for `__path` under `['fields]['__path']` and obviouls fails with ` Undefined index: __path`.
The PR attempts to fix it.
It should later be upmerged to 4.x and master.

BUGFIX: fix logic of getting __path from result

---

Classes/Driver/QueryInterface.php
Classes/Driver/Version1/Query/FilteredQuery.php
Classes/Driver/Version5/Query/FilteredQuery.php
Classes/Eel/ElasticSearchQueryBuilder.php
README.md

I still struggle to understand how it happened.
As I understand, it had to be so that changes in 3.0 branch had to be more recent than in 4.0. But how then would you explain things like reappearing of `TYPO3CR` in the readme?!
Fixes: #291

BUGFIX: fix upmerge gone wrong

---

composer.json

Version 3.0.0 of Flowpack.ElasticSearch was released some weeks ago which has support for ElasticSearch 5 and 6. The Flowpack.ElasticSearch.ContentreposiotryAdaptor however requires 2.x or dev-master. This PR modifies contentrepositoryadaptor to support version 3.x of Flowpack.ElasticSearch. Currently no installable combination working for Elasticsearch 5.x is possible.

Modified Flowpack.ElasticSearch requirement to include 3.X

---

composer.json

Version 3.0.0 of Flowpack.ElasticSearch was released some weeks ago which has support for ElasticSearch 5 and 6. The Flowpack.ElasticSearch.ContentreposiotryAdaptor however requires 2.x or dev-master. This PR modifies contentrepositoryadaptor to support version 3.x of Flowpack.ElasticSearch. Currently no installable combination working for Elasticsearch 5.x is possible.
Related to #299

TASK: Modified Flowpack.ElasticSearch requirement to include 3.X (Backport of #299)

---

Classes/Driver/Version5/DocumentDriver.php

After switching from ES 2.3 to ES 5.6.16 an error occured during changing the DocumentType in the neos backend:
```
Elasticsearch request failed. [GET http://elasticsearch:9200//_search/scroll?scroll=1m]: Array ( [root_cause] => Array ( [0] => Array ( [type] => illegal_argument_exception [reason] => request [//_search/scroll] contains unrecognized parameter: [scroll] ) ) [type] => illegal_argument_exception [reason] => request [//_search/scroll] contains unrecognized parameter: [scroll] ) ; Response body: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [//_search/scroll] contains unrecognized parameter: [scroll]"}],"type":"illegal_argument_exception","reason":"request [//_search/scroll] contains unrecognized parameter: [scroll]"},"status":400} Request data: …
```

BUGFIX: Move scroll parameter to POST body in Version5/DocumentDriver

---

.travis.yml
Classes/Eel/ElasticSearchQueryBuilder.php

For details see: https://discuss.neos.io/t/elasticsearch-special-chars-umlauts/4869

BUGFIX: Do not escape unicode characters for fulltext search

---

Classes/Driver/Version6/Mapping/NodeTypeMappingBuilder.php
Configuration/NodeTypes.yaml
Configuration/Settings.Neos.ContentRepository.Search.yaml
Configuration/Testing/NodeTypes.yaml
Documentation/ElasticMapping-5.x.md
README.md

The field type string was removed with Elasticsearch 5.
The adapter internally mapped string to either keyword
or text depending on the not_analyzed keyword.
This mapping is removed now. Please adjust your configuration.

!!! TASK: Remove fallback for fields with string mapping

---

Classes/Driver/AbstractQuery.php
Classes/Driver/Version6/Query/FilteredQuery.php
Configuration/NodeTypes.Override.Document.yaml
Configuration/Settings.yaml
Tests/Unit/Eel/ElasticSearchQueryBuilderTest.php

Index-time boosting is deprecated since elasticsearch 5.0.0.
Instead, the field mapping boost is applied at query time.
This has several advantages, especially boosting can be adjusted without reindexing  all nodes.
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-boost.html

!!! FEATURE: Refactor index-time boosting to query-time boosting

---

Classes/Driver/AbstractNodeTypeMappingBuilder.php
Classes/Driver/NodeTypeMappingBuilderInterface.php
Classes/Driver/Version6/DocumentDriver.php
Classes/Driver/Version6/Mapping/NodeTypeMappingBuilder.php
Classes/Indexer/NodeIndexer.php

Previously the nodeType name had to be altered to match
the constraints of an Elasticsearch type. As the type
is a simple field now, this is not needed anymore.

!!! TASK: Do not convert the nodeType name

---

Classes/Command/NodeIndexCommandController.php
Classes/Command/SearchCommandController.php
Classes/Driver/AbstractQuery.php
Classes/Driver/Version6/IndexerDriver.php
Classes/Eel/ElasticSearchQueryBuilder.php
Classes/Indexer/NodeIndexer.php
Configuration/NodeTypes.Override.Document.yaml
Configuration/NodeTypes.Override.Hidable.yaml
Configuration/NodeTypes.Override.Node.yaml
Configuration/NodeTypes.Override.Timable.yaml
Configuration/Settings.yaml
Migrations/Code/Version20200513223401.php
README.md
Tests/Functional/Eel/ElasticSearchQueryTest.php
Tests/Unit/Eel/ElasticSearchQueryBuilderTest.php

Previously fields that are not defined via properties have been started with an underscore or sometimes with two underscores. This is generally not a problem for elasticsearch but kibana treats these fields as elasticsearch-internal and doesn’t aloow to analyze them.
Now the fields follow the rules defined in https://www.elastic.co/guide/en/beats/devguide/current/event-conventions.html
The fields are renamed as follows:
| Old | New |
|-----|-----|
|__identifier |neos_node_identifier |
|__parentPath |neos_parent_path |
|__path |neos_path|
|__typeAndSupertypes|neos_type_and_supertypes|
|__workspace |neos_workspace|
|_creationDateTime|neos_creation_date_time|
|_hidden|neos_hidden|
|_hiddenBeforeDateTime |neos_hidden_before_datetime|
|_hiddenAfterDateTime|neos_hidden_after_datetime| …

WIP: !!! TASK: Rename fields to beats convention

---

Classes/Driver/Version6/DocumentDriver.php
Tests/Functional/Eel/ElasticSearchQueryTest.php
Tests/Functional/Indexer/NodeIndexerTest.php
Tests/Functional/Traits/ContentRepositoryNodeCreationTrait.php

Removal of nodes from the index was simply broken and failed (apart from the logs) silently.
Added a test for node indexing and deletion and fixed the issue.

BUGFIX: Do not specify a type when deleting nodes

---

Classes/Command/NodeIndexCommandController.php
Classes/Indexer/NodeIndexer.php

The return value of `ApiException->getResponse()` is no longer a
string, so decoding it as JSON fails.

BUGFIX: Trying to use response from exception as string

---

Classes/Eel/ElasticSearchQueryBuilder.php
Classes/Eel/ElasticSearchQueryResult.php

As the comment and code says, these might return `null`:
- `searchHitForNode()`
- `getFullElasticSearchHitForNode()`

BUGFIX: Make return type nullable

---

Classes/Eel/ElasticSearchQueryBuilder.php

When a query fails on Elasticsearch
- it will be logged now (before being sent to Elasticsearch)
- in case of an error a system log entry will be written
Fixes #340

BUGFIX: Fix logging of queries in case of an error

---

Classes/Eel/ElasticSearchQueryBuilder.php

Currently the EEL query builder logs the query request body. I added the indexname as we might be in multi-index scenarios.

Add indexname to log entries

---

Classes/Command/NodeIndexCommandController.php

BUGFIX: Set up missing alias during node indexing

---

Classes/Driver/Version6/Mapping/NodeTypeMappingBuilder.php

A follow-up to #372: Only filter null values, but keep false and any
other value considered `empty()` by PHP.
Related #375

TASK: Adjust filter allowing to unset elasticSearchMapping parameters

---

Classes/Command/SearchCommandController.php
Classes/Indexer/NodeIndexer.php
Classes/Indexer/WorkspaceIndexer.php
Classes/Service/IndexWorkspaceTrait.php
Tests/Functional/BaseElasticsearchContentRepositoryAdapterTest.php

This replaces the use of the `ContextFactory` of the ContentRepository package in several places with the `ContextFactoryInterface` instead.
That fixes failures like
```
Call to undefined method Neos\ContentRepository\Domain\Service\Context::getCurrentSiteNode() [...]
```
when expecting a *Neos*  context during indexing.
Fixes: #380

BUGFIX: Replace hard coded ContextFactory references with the interface

---

README.md

Removed whitespace from `nodetype: showIndexableConfiguration`

fix: Removed whitespace from `nodetype: showIndexableConfiguration`

---

Configuration/Settings.Neos.ContentRepository.Search.yaml

This sets ignore_above of keyword fields to 8191 according to
https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-above.html#ignore-above
which avoids "Document contains at least one immense term in field" errors
when indexing fields containing lots of text.

TASK: Configure ignore_above for keyword fields

---

composer.json

Changing `"^7.3` to `"^7.3 || ^8.0"` seems to be (almost) enough for me. 
Only bug I got in my checks was related to `\Neos\ContentRepository\Search\Eel\IndexingHelper::extractHtmlTags()`
There is a str_replace in it, which (oh wonder) only accepts strings as input. Since PHP 8, it doesn’t accept NULL-Values anymore. But if a property isn’t set, this leads to an error while indexing.  
I solved it by adding a condition in the NodeTypes: `fulltextExtractor: '${Indexing.extractHtmlTags(value ? value : "")}'`
But  I’m not sure, if that is something, we should handle for the user. It would be easy to also accept a NULL-value and set the method-property to an empty string, if NULL was given. So the user wouldn’t have to take care about (as it was with PHP 7)
It is quite possible that there are …

PHP 8 compatibility

---

Classes/Driver/AbstractQuery.php
Classes/Driver/QueryInterface.php
Classes/Eel/ElasticSearchQueryBuilder.php
README.md

Previously you only could define the highlighting for all fields
and no_match_size was automatically active. Now the parameters can be configured
individually by field.

FEATURE: Extended highlight configuration

---

README.md

`Indexing.Indexing.extractAssetContent(value)` › `Indexing.extractAssetContent(value)`

BUGIX: Fix typo in readme

---

Classes/Driver/Version6/DocumentDriver.php
Classes/Driver/Version6/IndexerDriver.php
Configuration/Settings.yaml
Tests/Functional/BaseElasticsearchContentRepositoryAdapterTest.php

- Remove _type argument, which is not needed for modern ES versions
- Fix removing of all indices in tests. Wildcard removal is not supported on Elasticsearch 8
- Add an alias for 8.x driver

FEATURE: Make the adapter Elasticsearch 8 compatible

---

Classes/Service/DocumentIdentifier/NodeIdentifierBasedDocumentIdentifierGenerator.php

@daniellienert implemented `NodeIdentifierBasedDocumentIdentifierGenerator` in #394, which works mostly fine. Except of a few cases where workspace names differ while publishing. 
#404 describes the same problem. Some of our tests showed up, that getting the workspace-name form the nodes context, helps out here. We stumbled over #404, which also includes dimension-values in the identifier. But this is not needed, since there are different ES indices per dimension-combination. So we do not need an additional info about the dimension inside the identifier. 
@daniellienert  and I have already discussed this change once via Slack and came to the conclusion that this is a logical fix. We then successfully tested this in customer projects. 
This change should appear as a minor release. It is …

Bugfix: Use workspace name from context

---

Classes/Indexer/NodeIndexer.php

When the nodes get indexed by the RealTimeCatchUpHook it might happen, the projection caugt up events of a different user/workspace. So the indexing must run without security checks.

BUGFIX: Find nodes in CR without security checks to allow nodes of other workspaces
